ci: :bug: Adjust the installation of WebView2

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -114,6 +114,10 @@ jobs:
       - name: Install system dependencies
         run: |
           choco install -y nsis nodejs-lts ffmpeg
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.x'
       - name: Install pnpm
         uses: pnpm/action-setup@v4
         with:
@@ -129,7 +133,13 @@ jobs:
           pnpm lint
       - name: Install WebView2
         run: |
-          winget install --id Microsoft.EdgeWebView2Runtime -e --silent
+          curl -o WebView2Installer.exe https://go.microsoft.com/fwlink/p/?LinkId=2124703
+          if (Test-Path "WebView2Installer.exe") {
+            Start-Process -FilePath WebView2Installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait
+          } else {
+            echo "Failed to download WebView2 installer"
+            exit 1
+          }
       - name: Test backend
         working-directory: ./src-tauri
         run: |
