3 cortar video ffmpeg (#36)
* feat: :sparkles: Try to play video on app

* fix: :wrench: Enable assets protocol

* feat: cut_video function call

* feat(ffmpeg): :recycle: Use select filter instead of several cuts

* feat(ffmpeg): :recycle: Use precompiled static binaries instead of ffmpeg-next

* feat: :bricks: Add executables to git lfs

* refactor: :recycle: Refactor structure to allow app testing

* feat(menu): :white_check_mark: Add tests

* fix: :rotating_light: Clippy errors

* fix: :bug: Several fixes

* feat: :green_heart: Refactor CI build to use cache and make parallel jobs

* fix: :green_heart: Add PNPM to workflow

* fix: :green_heart: Use latest version of cache action

* refactor: :green_heart: Move stages around

* fix: :green_heart: Upgrade action version

* fix: :green_heart: Specify subdirectory for cache

---------

Co-authored-by: Edith <eddith@proton.me>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,153 +1,59 @@
 name: build
 on:
   pull_request:
+  push:
+    branches:
+      - main
 jobs:
-  linux:
-    name: Linux - Build, test and lint
-    runs-on: ubuntu-latest
-    env:
-      PKG_CONFIG_PATH: /usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/share
+  build-lint:
+    strategy:
+      fail-fast: false
+      matrix:
+        platform: [windows-latest, macos-latest, ubuntu-latest]
+        rust:
+          - stable
+        include:
+          - platform: 'macos-latest' # for Arm based macs (M1 and above).
+            args: '--target aarch64-apple-darwin'
+          - platform: 'macos-latest' # for Intel based macs.
+            args: '--target x86_64-apple-darwin'
+          - platform: 'ubuntu-latest'
+            args: ''
+          - platform: 'windows-latest'
+            args: ''
+
+    runs-on: ${{ matrix.platform }}
+
     steps:
       - uses: actions/checkout@v2
+
       - name: Update system repositories
+        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
         run: |
           sudo apt-get update
+
       - name: Install system dependencies
+        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
         run: |
-          sudo apt-get install -y \
-              curl wget unzip \
-              build-essential cmake pkg-config \
-              libgtk-3-dev libgdk-pixbuf2.0-dev \
-              libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev \
-              libsoup-3.0-dev \
-              libclang-dev clang \
-              libssl-dev libxdo-dev file\
-              libavutil-dev libavformat-dev libavfilter-dev \
-              libavdevice-dev \
-              libayatana-appindicator3-dev librsvg2-dev \
-              libx11-dev libxcb1-dev libx11-xcb-dev libxcomposite-dev \
-              libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev \
-              libxi-dev libxrandr-dev libxrender-dev libxtst-dev \
-              libasound2-dev libudev-dev libfreetype6-dev zlib1g-dev \
-              libnss3-dev libxss-dev libdbus-1-dev libxkbcommon-dev \
-              fuse libfuse2 desktop-file-utils xdg-utils
+          sudo apt-get install libwebkit2gtk-4.1-dev \
+            build-essential \
+            curl \
+            wget \
+            file \
+            libxdo-dev \
+            libssl-dev \
+            libayatana-appindicator3-dev \
+            librsvg2-dev
+
       - name: Install LinuxDeploy
+        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
         uses: miurahr/install-linuxdeploy-action@v1
         with:
           plugins: gstreamer appimage
           dir: /usr/local/bin
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '20'
-      - uses: pnpm/action-setup@v4
-        with:
-          run_install: true
-      - name: Install dependencies
-        run: |
-          pnpm install
-      - name: Test frontend
-        run: |
-          pnpm test
-      - name: Lint frontend
-        run: |
-          pnpm lint
-      - name: Test backend
-        working-directory: ./src-tauri
-        run: |
-          cargo test
-      - name: Lint backend
-        working-directory: ./src-tauri
-        run: |
-          cargo clippy -- -D warnings
-      - name: Format backend
-        working-directory: ./src-tauri
-        run: |
-          cargo fmt -- --check
-      - name: Build project
-        run: |
-          pnpm tauri build
-  macos:
-    name: MacOS - Build, test and lint
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Install system dependencies
-        run: |
-          brew install pkg-config ffmpeg
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '20'
-      - uses: pnpm/action-setup@v4
-        with:
-          run_install: true
-      - name: Test frontend
-        run: |
-          pnpm test
-      - name: Lint frontend
-        run: |
-          pnpm lint
-      - name: Build project
-        run: |
-          pnpm tauri build
-      - name: Test backend
-        working-directory: ./src-tauri
-        run: |
-          cargo test
-      - name: Lint backend
-        working-directory: ./src-tauri
-        run: |
-          cargo clippy -- -D warnings
-      - name: Format backend
-        working-directory: ./src-tauri
-        run: |
-          cargo fmt -- --check
-  windows:
-    name: Windows - Build, test and lint
-    runs-on: windows-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Rust toolchain
-        uses: dtolnay/rust-toolchain@stable
-        with:
-          targets: x86_64-pc-windows-msvc
-      - name: Cache vcpkg
-        id: cache-vcpkg
-        uses: actions/cache@v4
-        with:
-          path: C:\vcpkg
-          key: vcpkg-${{ runner.os }}-${{ hashFiles('.github/workflows/build.yaml') }}
-          restore-keys: |
-            vcpkg-${{ runner.os }}
-      - name: Install system dependencies
-        run: |
-          choco install -y nsis nodejs-lts ffmpeg pkgconfiglite
-      - name: Install vcpkg and ffmpeg
-        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
-        run: |
-          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
-          cd C:\vcpkg
-          .\bootstrap-vcpkg.bat
-          .\vcpkg integrate install
-          .\vcpkg install ffmpeg:x64-windows
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.x'
-      - name: Install pnpm
-        uses: pnpm/action-setup@v4
-        with:
-          run_install: true
-      - name: Install dependencies
-        run: |
-          pnpm install
-      - name: Test frontend
-        run: |
-          pnpm test
-      - name: Lint frontend
-        run: |
-          pnpm lint
+
       - name: Install WebView2
+        if: matrix.platform == 'windows-latest' # This must match the platform value defined above.
         run: |
           Remove-Item -Path WebView2Installer.exe -ErrorAction Ignore
           Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "WebView2Installer.exe"
@@ -157,26 +63,137 @@ jobs:
             echo "Failed to download WebView2 installer"
             exit 1
           }
-      - name: Set env variables
-        run: |
-          echo "VCPKG_ROOT=C:\\vcpkg" >> $GITHUB_ENV
-          echo "C:\\vcpkg" >> $GITHUB_PATH
-          echo "PKG_CONFIG_PATH=C:\\vcpkg\\installed\\x64-windows\\lib\\pkgconfig" >> $GITHUB_ENV
-      - name: Debug env
-        run: |
-          echo $GITHUB_ENV
-      - name: Test backend
-        working-directory: ./src-tauri
-        run: |
-          cargo test
-      - name: Lint backend
-        working-directory: ./src-tauri
-        run: |
-          cargo clippy -- -D warnings
+
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20.x
+
+      - uses: pnpm/action-setup@v4
+        with:
+          run_install: true
+
+      - name: Install Rust stable
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
+          targets: ${{ (matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin') || (matrix.platform == 'windows-latest' && 'x86_64-pc-windows-msvc') || '' }}
+
+      - uses: Swatinem/rust-cache@v2
+        with:
+          shared-key: ${{ matrix.platform }}
+          key: v1 # increment this to bust the cache if needed
+          workspaces: src-tauri
+
+      - name: Install frontend dependencies
+        run: pnpm install
+
       - name: Format backend
         working-directory: ./src-tauri
         run: |
           cargo fmt -- --check
+
       - name: Build project
         run: |
           pnpm tauri build
+
+      - name: Lint backend
+        working-directory: ./src-tauri
+        run: |
+          cargo clippy -- -D warnings
+
+      - name: Lint frontend
+        run: |
+          pnpm lint
+
+  test:
+    strategy:
+      fail-fast: false
+      matrix:
+        platform: [windows-latest, macos-latest, ubuntu-latest]
+        rust:
+          - stable
+        include:
+          - platform: 'macos-latest' # for Arm based macs (M1 and above).
+            args: '--target aarch64-apple-darwin'
+          - platform: 'macos-latest' # for Intel based macs.
+            args: '--target x86_64-apple-darwin'
+          - platform: 'ubuntu-latest'
+            args: ''
+          - platform: 'windows-latest'
+            args: ''
+
+    runs-on: ${{ matrix.platform }}
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Update system repositories
+        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
+        run: |
+          sudo apt-get update
+
+      - name: Install system dependencies
+        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
+        run: |
+          sudo apt-get install libwebkit2gtk-4.1-dev \
+            build-essential \
+            curl \
+            wget \
+            file \
+            libxdo-dev \
+            libssl-dev \
+            libayatana-appindicator3-dev \
+            librsvg2-dev
+
+      - name: Install LinuxDeploy
+        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
+        uses: miurahr/install-linuxdeploy-action@v1
+        with:
+          plugins: gstreamer appimage
+          dir: /usr/local/bin
+
+      - name: Install WebView2
+        if: matrix.platform == 'windows-latest' # This must match the platform value defined above.
+        run: |
+          Remove-Item -Path WebView2Installer.exe -ErrorAction Ignore
+          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "WebView2Installer.exe"
+          if (Test-Path "WebView2Installer.exe") {
+            Start-Process -FilePath WebView2Installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait
+          } else {
+            echo "Failed to download WebView2 installer"
+            exit 1
+          }
+
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20.x
+
+      - uses: pnpm/action-setup@v4
+        with:
+          run_install: true
+
+      - name: Install Rust stable
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
+          targets: ${{ (matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin') || (matrix.platform == 'windows-latest' && 'x86_64-pc-windows-msvc') || '' }}
+
+      - uses: Swatinem/rust-cache@v2
+        with:
+          shared-key: ${{ matrix.platform }}
+          key: v1 # increment this to bust the cache if needed
+          workspaces: src-tauri
+
+      - name: Install frontend dependencies
+        run: pnpm install
+
+      - name: Test frontend
+        run: |
+          pnpm test
+
+      - name: Test backend
+        working-directory: ./src-tauri
+        run: |
+          cargo test --tests
